显示所有证书

diff --git a/.github/workflows/install.yml b/.github/workflows/install.yml
--- a/.github/workflows/install.yml
+++ b/.github/workflows/install.yml
@@ -97,29 +97,29 @@ jobs:
             target_arch: arm64
             python_arch: arm64
 
-          - os: ubuntu-latest
-            platform: linux
-            arch: x86_64
-            target_arch: x86_64
-            python_arch: x64
-
-          - os: ubuntu-24.04-arm
-            platform: linux
-            arch: aarch64
-            target_arch: arm64
-            python_arch: arm64
-            
-          - os: windows-latest
-            platform: win
-            arch: x86_64
-            target_arch: x86_64
-            python_arch: x64
-            
-          - os: windows-11-arm
-            platform: win
-            arch: aarch64
-            target_arch: arm64
-            python_arch: arm64
+         # - os: ubuntu-latest
+         #   platform: linux
+         #   arch: x86_64
+         #   target_arch: x86_64
+         #   python_arch: x64
+#
+         # - os: ubuntu-24.04-arm
+         #   platform: linux
+         #   arch: aarch64
+         #   target_arch: arm64
+         #   python_arch: arm64
+         #   
+         # - os: windows-latest
+         #   platform: win
+         #   arch: x86_64
+         #   target_arch: x86_64
+         #   python_arch: x64
+         #   
+         # - os: windows-11-arm
+         #   platform: win
+         #   arch: aarch64
+         #   target_arch: arm64
+         #   python_arch: arm64
 
       fail-fast: false
 
@@ -146,6 +146,14 @@ jobs:
           
           # 清理
           rm certificate.p12
+
+          security find-identity -v -p codesigning
+          # 检查证书是否导入成功
+          security find-identity -v -p codesigning | grep "overflow65537 Developer Certificate"
+          if [[ $? -ne 0 ]]; then
+            echo "Certificate import failed"
+            exit 1
+          fi
  
       - name: Set up Python
         uses: actions/setup-python@v4
